---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Behavioral effects of dog activity

## Load Packages
```{r, message=FALSE, warning=FALSE, error=FALSE}
library(tidyverse)
library(lubridate)
library(readr)
library(stringr)
```

## Data input

```{r}
data_set <- read_rds("data/my_data_set_2.rds")
data_set <- data_set |> 
  mutate(
    species = ifelse(species == "Dasypsu", "Dasypus", species),
    conservation_unit = ifelse(str_detect(conservation_unit,"Furnas"),"Furnas",conservation_unit)
  )
glimpse(data_set)
```

## identifying points with `m/e`  cameras and setting the `date_time` 

```{r}
data_set <- data_set |> 
  mutate(
   m_e= str_detect(station, "\\(m/e\\)"),
   station = str_remove(station, "\\(m/e\\)"),
   station = ifelse(station == "NA", NA, as.numeric(station)),
   date_time = ymd_hms(paste(date, time))
   )
glimpse(data_set)
```

# Quick view of 'capture' frequency 

```{r}
data_set |> 
  ggplot(aes(x=date,y=time,color=conservation_unit)) +
  geom_line() + 
  geom_point() +
  facet_wrap(~conservation_unit, scale="free", nrow = 5)
```

# Identify the pray and predator

```{r}
pray <- c("Dasypus", "Cabassous", "Euphractus")
data_set <- data_set |> 
  mutate(
    type = ifelse(species %in% pray, "pray", "predator")
  )
glimpse(data_set)
```


# Calculating the time

```{r}
data_set_aux <- data_set |> 
  arrange(conservation_unit, mestre, station, date_time)

data_set_aux$diff_time <- NA
for(i in 1:(nrow(data_set_aux)-1)){
  unit_con <- data_set_aux$conservation_unit[i]
  mestre <- data_set_aux$mestre[i]
  station <- data_set_aux$station[i]
  if((unit_con == data_set_aux$conservation_unit[i+1] &
     mestre == data_set_aux$mestre[i+1] &
      station == data_set_aux$station[i+1]) | is.na(data_set_aux$station[i+1]) ){
    if(data_set_aux$type[i] == "predator" & 
       data_set_aux$type[i+1] == "pray"){
      data_set_aux$diff_time[i] =  as.numeric(
        difftime(
          data_set_aux$date_time[i+1], data_set_aux$date_time[i],units = "hours"))
       }
  }else{
        data_set_aux$diff_time[i] <- NA
      }
}
writexl::write_xlsx(data_set_aux,"data/banco_de_dados.xlsx")
```







